project:
  type: website

website:
  title: "Gracie Hayes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: pres.qmd
        text: Posters & Presentations
      - text: CV
        href: Hayes_CV_2025.pdf

format:
  html:
    theme: 
      - stylesheet1.scss
    mainfont: Montserrat
    toc: true
    link-external-newwindow: true

# format:
#   html:
#     theme:
#       - cosmo
#       - brand
#     css: styles.css
#     toc: true

execute:
  freeze: auto

resources:
  - Hayes_CV_2025.pdf
  
