project:
  type: website

website:
  title: "ghayes"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - courses
    right:
      - text: CV
        href: Hayes_CV_2025.pdf

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute:
  freeze: auto

